filter_sequence:
  - DEFAULT_IGNORE_PATTERNS
  - CODE_PATTERNS
  - LATEX_PATTERNS
  - CITATION_PATTERNS
  - METADATA_PATTERNS
  - NAVIGATION_PATTERNS
  - SEQUENCE_PATTERNS
  - FORMATTING_PATTERNS
